### ISSUE TITLE
Check the existence of the file before opening it

### ISSUE THREAD

**Issue by xibr** [TachibanaGeneralLaboratories/download-navi#164]
In the list of completed downloads you must check if the file exists before opening it. If it does not exist, please show a message that the file does not exist or has been deleted, something like that.

**Comment by xibr** [comment]
i'm not sure if this is correct way to do this

https://github.com/TachibanaGeneralLaboratories/download-navi/blob/82d7e1ebadc8bc14feee693ea8c2d16cc61ca919/app/src/main/java/com/tachibana/downloader/core/utils/Utils.java#L658-L663

```
public static Intent createOpenFileIntent(@NonNull Context context, @NonNull DownloadInfo info) {
        FileSystemFacade fs = SystemFacadeHelper.getFileSystemFacade(context);
        Uri filePath = fs.getFileUri(info.dirPath, info.fileName);
        DocumentFile file = DocumentFile.fromSingleUri(context, filePath);
        if (file.exists())
            return createOpenFileIntent(context, filePath, info.mimeType);
        else
            return null;
    }
```
https://github.com/TachibanaGeneralLaboratories/download-navi/blob/82d7e1ebadc8bc14feee693ea8c2d16cc61ca919/app/src/main/java/com/tachibana/downloader/ui/main/FinishedDownloadsFragment.java#L125-L131
```
@Override
    public void onItemClicked(@NonNull DownloadItem item) {
        if (Utils.createOpenFileIntent(activity.getApplicationContext(), item.info) != null) {
            startActivity(Intent.createChooser(
                    Utils.createOpenFileIntent(activity.getApplicationContext(), item.info),
                    getString(R.string.open_using)));
        } else {
            Toast.makeText(activity.getApplicationContext(), "this file not available!", Toast.LENGTH_SHORT).show();
        }
    }
```

**Comment by proninyaroslav** [comment]
@xibr 
Any help would be greatly appreciated. There are two notes about the code:
1. Don't use `DocumentFile.fromSingleUri(context, filePath);` directly, just implement `exists()` method in FileSystemFacade for SAF and classic filesystem.
2. Don't duplicate the code: call `Utils.createOpenFileIntent()` once, write to the variable, and check it for null value.

**Comment by xibr** [comment]
I tried to implement it but failed, I have this crash, I will give another try tomorrow.

```
 --------- beginning of crash
2021-07-10 23:56:28.118 1113-1113/com.tachibana.downloader E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tachibana.downloader, PID: 1113
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getScheme()' on a null object reference
        at com.tachibana.downloader.core.system.SafFileSystem.isSafPath(SafFileSystem.java:193)
        at com.tachibana.downloader.core.utils.Utils.isSafPath(Utils.java:555)
        at com.tachibana.downloader.core.system.FsModuleResolverImpl.resolveFsByUri(FsModuleResolverImpl.java:46)
        at com.tachibana.downloader.core.system.FileSystemFacadeImpl.exists(FileSystemFacadeImpl.java:529)
        at com.tachibana.downloader.core.utils.Utils.createOpenFileIntent(Utils.java:654)
        at com.tachibana.downloader.ui.main.FinishedDownloadsFragment.onItemClicked(FinishedDownloadsFragment.java:129)
        at com.tachibana.downloader.ui.main.DownloadListAdapter$ViewHolder.lambda$bind$0$DownloadListAdapter$ViewHolder(DownloadListAdapter.java:184)
        at com.tachibana.downloader.ui.main.-$$Lambda$DownloadListAdapter$ViewHolder$E8d_VzQkiVG_5RFgzfe3hLQfehM.onClick(Unknown Source:6)
        at android.view.View.performClick(View.java:7862)
        at android.view.View.performClickInternal(View.java:7831)
        at android.view.View.access$3600(View.java:879)
        at android.view.View$PerformClick.run(View.java:29359)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
2021-07-10 23:56:28.119 1113-1113/com.tachibana.downloader E/ACRA: ACRA caught a NullPointerException for com.tachibana.downloader
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getScheme()' on a null object reference
        at com.tachibana.downloader.core.system.SafFileSystem.isSafPath(SafFileSystem.java:193)
        at com.tachibana.downloader.core.utils.Utils.isSafPath(Utils.java:555)
        at com.tachibana.downloader.core.system.FsModuleResolverImpl.resolveFsByUri(FsModuleResolverImpl.java:46)
        at com.tachibana.downloader.core.system.FileSystemFacadeImpl.exists(FileSystemFacadeImpl.java:529)
        at com.tachibana.downloader.core.utils.Utils.createOpenFileIntent(Utils.java:654)
        at com.tachibana.downloader.ui.main.FinishedDownloadsFragment.onItemClicked(FinishedDownloadsFragment.java:129)
        at com.tachibana.downloader.ui.main.DownloadListAdapter$ViewHolder.lambda$bind$0$DownloadListAdapter$ViewHolder(DownloadListAdapter.java:184)
        at com.tachibana.downloader.ui.main.-$$Lambda$DownloadListAdapter$ViewHolder$E8d_VzQkiVG_5RFgzfe3hLQfehM.onClick(Unknown Source:6)
        at android.view.View.performClick(View.java:7862)
        at android.view.View.performClickInternal(View.java:7831)
        at android.view.View.access$3600(View.java:879)
        at android.view.View$PerformClick.run(View.java:29359)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

```

**Comment by proninyaroslav** [comment]
You are not checking that the Uri can be null inside the `exists` method.
