### ISSUE TITLE
Bromite WebView support

### ISSUE THREAD

**Issue by proninyaroslav** [TachibanaGeneralLaboratories/download-navi#46]
```
android.util.AndroidRuntimeException: java.lang.reflect.InvocationTargetException
	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:270)
	at android.webkit.WebSettings.getDefaultUserAgent(WebSettings.java:1270)
	at com.tachibana.downloader.core.system.SystemFacadeImpl.getSystemUserAgent(SystemFacadeImpl.java:74)
	at com.tachibana.downloader.core.settings.SettingsRepositoryImpl$Default.userAgent(SettingsRepositoryImpl.java:80)
	at com.tachibana.downloader.core.settings.SettingsRepositoryImpl.userAgent(SettingsRepositoryImpl.java:459)
	at com.tachibana.downloader.ui.adddownload.AddDownloadViewModel.getPrefUserAgent(AddDownloadViewModel.java:153)
	at com.tachibana.downloader.ui.adddownload.AddDownloadDialog.initParams(AddDownloadDialog.java:240)
	at com.tachibana.downloader.ui.adddownload.AddDownloadDialog.onCreate(AddDownloadDialog.java:223)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2586)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:838)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2663)
	at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:246)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:542)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
	at android.app.Activity.performStart(Activity.java:7165)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2972)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1813)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6671)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:265)
	... 35 more
Caused by: java.lang.RuntimeException: Cannot load WebView
	at org.chromium.android_webview.AwBrowserProcess.a(PG:24)
	at com.android.webview.chromium.WebViewChromiumFactoryProvider.a(PG:81)
	at com.android.webview.chromium.WebViewChromiumFactoryProvider.<init>(PG:12)
	at com.android.webview.chromium.WebViewChromiumFactoryProviderForP.<init>(PG:1)
	at com.android.webview.chromium.WebViewChromiumFactoryProviderForP.create(PG:1)
	... 37 more
Caused by: he
	at org.chromium.base.library_loader.LibraryLoader.a(PG:33)
	at org.chromium.base.library_loader.LibraryLoader.a(PG:13)
	at org.chromium.android_webview.AwBrowserProcess.a(PG:20)
	... 41 more
Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "\/system\/app\/webview\/webview.apk"],nativeLibraryDirectories=[\/system\/app\/webview\/lib\/arm64, \/system\/app\/webview\/webview.apk!\/lib\/arm64-v8a, \/system\/lib64, \/vendor\/lib64, \/system\/lib64, \/vendor\/lib64]]] couldn't find "libwebviewchromium.so"
	at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
	at java.lang.System.loadLibrary(System.java:1669)
	at org.chromium.base.library_loader.LibraryLoader.a(PG:24)
	... 43 more
```

**Comment by proninyaroslav** [comment]
This is a known issue. Solution: https://github.com/bromite/bromite/wiki/Installing-SystemWebView#troubleshooting
