### ISSUE TITLE
Deleting multiple files caused crash

### ISSUE THREAD

**Issue by rancidfrog** [TachibanaGeneralLaboratories/download-navi#56]
```
java.lang.IllegalStateException: Range start point not set.
	at androidx.core.util.Preconditions.checkState(Preconditions.java:96)
	at androidx.recyclerview.selection.DefaultSelectionTracker.extendProvisionalRange(DefaultSelectionTracker.java:281)
	at androidx.recyclerview.selection.GestureSelectionHelper.extendSelection(GestureSelectionHelper.java:214)
	at androidx.recyclerview.selection.GestureSelectionHelper.handleMoveEvent(GestureSelectionHelper.java:191)
	at androidx.recyclerview.selection.GestureSelectionHelper.handleTouch(GestureSelectionHelper.java:146)
	at androidx.recyclerview.selection.GestureSelectionHelper.onInterceptTouchEvent(GestureSelectionHelper.java:100)
	at androidx.recyclerview.selection.TouchEventRouter.onInterceptTouchEvent(TouchEventRouter.java:91)
	at androidx.recyclerview.widget.RecyclerView.findInterceptingOnItemTouchListener(RecyclerView.java:3151)
	at androidx.recyclerview.widget.RecyclerView.onInterceptTouchEvent(RecyclerView.java:3170)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2175)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2636)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2636)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2636)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2636)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2636)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2636)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2636)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2636)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2636)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2636)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2636)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2636)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:413)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1825)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3125)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:375)
	at android.view.View.dispatchPointerEvent(View.java:10283)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4530)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4361)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3901)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3954)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3920)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4047)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3928)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4104)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3901)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3954)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3920)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3928)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3901)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6360)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6334)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6280)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6463)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:177)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6434)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6486)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:943)
	at android.view.Choreographer.doCallbacks(Choreographer.java:755)
	at android.view.Choreographer.doFrame(Choreographer.java:684)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:929)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6334)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

Never happened before, though, when deleting multiple files.

**Comment by proninyaroslav** [comment]
Hi. Which version are you using?

**Comment by rancidfrog** [comment]
￼

**Comment by proninyaroslav** [comment]
This is probably a bug in one of the Android libraries, check it out in the next version. Feel free to open issue if it comes again.
