### ISSUE TITLE
Changing system language to Arabic caused crashing

### ISSUE THREAD

**Issue by phwright** [TachibanaGeneralLaboratories/download-navi#73]
When my device language was english it worked perfectly. After changing the system language to arabic, my whole device (lg g6) would half reboot (I don't know how else to describe it)

**Comment by proninyaroslav** [comment]
Hi. Are you using the latest version (1.1.1)? I checked and it works fine:

![Screenshot_1589035225](https://user-images.githubusercontent.com/7840559/81476805-7f421c00-921c-11ea-83b6-5d1e76fd98d4.png)

**Comment by proninyaroslav** [comment]
Also do you get crash right after launching the app?

**Comment by phwright** [comment]
Yep. I am using 1.1.1 from f-droid. I also tried installing it from google play, but the issue is still there. And yes, it crashes instantly.

**Comment by proninyaroslav** [comment]
Can you get a log using adb?

**Comment by phwright** [comment]
Should I just run logcat? Sorry I'm new to this.

**Comment by proninyaroslav** [comment]
Yes, during app starting

**Comment by proninyaroslav** [comment]
Sorry, accidentally closed :D

**Comment by phwright** [comment]
[Download-navi crash.txt](https://github.com/TachibanaGeneralLaboratories/download-navi/files/4604004/Download-navi.crash.txt)

**Comment by proninyaroslav** [comment]
I see in large numbers the following error. And not only for Navi. Can you tell me the exact time of the crash? It’s easier for me to understand in the log whether this error is the cause of the crash.

```
05-05 17:38:45.586 17082 17082 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tachibana.downloader/com.tachibana.downloader.ui.main.MainActivity}: java.lang.RuntimeException: android.os.DeadObjectException
05-05 17:38:45.586 17082 17082 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2858)
05-05 17:38:45.586 17082 17082 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2933)
05-05 17:38:45.586 17082 17082 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
05-05 17:38:45.586 17082 17082 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1612)
05-05 17:38:45.586 17082 17082 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
05-05 17:38:45.586 17082 17082 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
05-05 17:38:45.586 17082 17082 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6710)
05-05 17:38:45.586 17082 17082 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-05 17:38:45.586 17082 17082 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
05-05 17:38:45.586 17082 17082 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
05-05 17:38:45.586 17082 17082 E AndroidRuntime: Caused by: java.lang.RuntimeException: android.os.DeadObjectException
05-05 17:38:45.586 17082 17082 E AndroidRuntime: 	at android.os.storage.StorageManager.isUserKeyUnlocked(StorageManager.java:1323)
05-05 17:38:45.586 17082 17082 E AndroidRuntime: 	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:387)
05-05 17:38:45.586 17082 17082 E AndroidRuntime: 	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:371)
05-05 17:38:45.586 17082 17082 E AndroidRuntime: 	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:167)
05-05 17:38:45.586 17082 17082 E AndroidRuntime: 	at android.preference.PreferenceManager.getDefaultSharedPreferences(PreferenceManager.java:526)
05-05 17:38:45.586 17082 17082 E AndroidRuntime: 	at com.tachibana.downloader.ui.main.MainActivity.initDrawer(MainActivity.java:198)
05-05 17:38:45.586 17082 17082 E AndroidRuntime: 	at com.tachibana.downloader.ui.main.MainActivity.initLayout(MainActivity.java:167)
05-05 17:38:45.586 17082 17082 E AndroidRuntime: 	at com.tachibana.downloader.ui.main.MainActivity.onCreate(MainActivity.java:137)
05-05 17:38:45.586 17082 17082 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6982)
05-05 17:38:45.586 17082 17082 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
05-05 17:38:45.586 17082 17082 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2811)
05-05 17:38:45.586 17082 17082 E AndroidRuntime: 	... 9 more
05-05 17:38:45.586 17082 17082 E AndroidRuntime: Caused by: android.os.DeadObjectException
05-05 17:38:45.586 17082 17082 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
05-05 17:38:45.586 17082 17082 E AndroidRuntime: 	at android.os.BinderProxy.transact(Binder.java:766)
05-05 17:38:45.586 17082 17082 E AndroidRuntime: 	at android.os.storage.IStorageManager$Stub$Proxy.isUserKeyUnlocked(IStorageManager.java:2105)
05-05 17:38:45.586 17082 17082 E AndroidRuntime: 	at android.os.storage.StorageManager.isUserKeyUnlocked(StorageManager.java:1321)
05-05 17:38:45.586 17082 17082 E AndroidRuntime: 	... 19 more
05-05 17:38:45.610 20388 20388 E AndroidRuntime: FATAL EXCEPTION: main
```

**Comment by phwright** [comment]
I don't understand what you mean by the exact time. The phone reboots as soon as I open navi regardless of time (morning, noon, night). This doesn't happen with any other app.

**Comment by proninyaroslav** [comment]
I need the exact crash time so that I can find it in the log. Each log entry has a timestamp.

**Comment by phwright** [comment]
And how am I supposed to know that?

**Comment by proninyaroslav** [comment]
Just while logging, see how much time is on the phone’s watch at the time of the crash :)

**Comment by phwright** [comment]
But the whole log is a few seconds long.

**Comment by proninyaroslav** [comment]
Apparently the old data got into the log ... Ok, I found a crash point at the end of the log:
```
sendBroadcast:431 com.lge.mlt.providers.LDBSmartCareTrigger.sendMsgSmartCare:33 com.lge.mlt.providers.LDBMainLogProvider.insert:273 android.content.ContentProvider$Transport.insert:268 
ActivityManager: Start proc 32164:com.tachibana.downloader/u0a766 for activity com.tachibana.downloader/.ui.main.MainActivity
Process : Sending signal. PID: 24928 SIG: 9
InstalledAppProviderSer: insertAppIntoDb com.android.systemui
AndroidRuntime: FATAL EXCEPTION: LDBExceptionReporterHandlerThread
AndroidRuntime: Process: com.lge.mlt, PID: 26255
AndroidRuntime: DeadSystemException: The system died; earlier logs will point to the root cause
```
But this doesn't give an idea of the cause. Either your LG OS intercepts the error and doesn't show it, or this is the problem in the LG OS itself. Are there any crash reports available on your LG OS so you can watch them?

**Comment by proninyaroslav** [comment]
Please check it in 1.2, feel free to open again.
